#Frontend Dockerfile for Angular Application with Nginx

# --- STAGE 1: Build the Angular application ---
FROM node:20-alpine AS build-stage

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to leverage Docker layer caching
COPY package*.json ./

# Install dependencies (only run if package.json changes)
RUN npm install

# Copy the rest of the source code
COPY . .

# Build the Angular application in production mode
RUN npm run build -- --configuration production --base-href /

# --- STAGE 2: Serve the application (Production Stage) ---
FROM nginx:alpine AS production-stage

# Copy the built Angular files from the build stage
COPY --from=build-stage /app/dist/frontend/browser /usr/share/nginx/html
RUN chmod -R 755 /usr/share/nginx/html

# Remove the default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# This loads your routing logic while preserving Nginx's core settings (including MIME types).
COPY nginx.conf /etc/nginx/conf.d/default.conf

# The default Nginx port
EXPOSE 80

# The container will run Nginx to serve the site
CMD ["nginx", "-g", "daemon off;"]
