spring.application.name=cityVibes

# Set a default profile (e.g., 'dev' for local H2)
spring.profiles.default=dev
# Common server settings
server.port=8080
# Logging settings
logging.level.com.cityVibes=INFO
logging.level.org.springframework.web=INFO
# Security (JWT configuration details would go here if shared)


# Swagger settings

# Swagger UI path
springdoc.swagger-ui.path=/swagger-ui
# These tell the Swagger UI where to find the JSON docs via the proxy
springdoc.swagger-ui.url=/cityVibes/v3/api-docs
springdoc.swagger-ui.config-url=/cityVibes/v3/api-docs/swagger-config
server.forward-headers-strategy=framework
springdoc.swagger-ui.display-query-params-extension=true
# This property disables the default /swagger-ui.html endpoint,
springdoc.swagger-ui.disable-swagger-default-url=true

# Debugging
#logging.level.root=DEBUG
#spring.jackson.serialization.write-dates-as-timestamps=false

# Metrics
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

spring.security.user.name=${PROMETHEUS_USER:fallbackUser123}
spring.security.user.password=${PROMETHEUS_PASSWORD:fallbackPassword123}

# Photo upload
upload.path=${UPLOAD_DIR:/tmp/uploads}